[project]
name = "nilvec"
version = "0.1.0"
description = "Concurrent Vector Index Implementations for ANN Search"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h5py",
    "matplotlib",
    "numpy",
    "requests",
    "faiss-cpu",  # Assuming CPU version for easier installation, or optional
    "usearch"
]

[build-system]
requires = ["meson-python", "ninja", "pybind11"]
build-backend = "mesonpython"

[tool.meson-python.args]
setup = ["-Duse_hdf5=true"]
